# Disease prediction using Machine Learning Dataset from Kaggle

In [1]:
# Importing necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [145]:
# Import datatset
df = pd.read_csv('Training.csv')
df.head()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          1                     1                    0          0   
2        1          0                     1                    0          0   
3        1          1                     0                    0          0   
4        1          1                     1                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  scurring  \
0       0           0             0        0                 0  ...         0   
1       0           0             0        0                 0  ...         0   
2       0           0             0        0                 0  ...         0   
3       0           0             0        0                 0  ...         0   
4       0           0             0        0                 0  ...         0   

   skin_peeling  silver_like_dusting  small_dents_in_nails  \
0             0                    0                     0   
1             0                    0                     0   
2             0                    0                     0   
3             0                    0                     0   
4             0                    0                     0   

   inflammatory_nails  blister  red_sore_around_nose  yellow_crust_ooze  \
0                   0        0                     0                  0   
1                   0        0                     0                  0   
2                   0        0                     0                  0   
3                   0        0                     0                  0   
4                   0        0                     0                  0   

          prognosis  Unnamed: 133  
0  Fungal infection           NaN  
1  Fungal infection           NaN  
2  Fungal infection           NaN  
3  Fungal infection           NaN  
4  Fungal infection           NaN  

[5 rows x 134 columns]

In [5]:
# data visualisation
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4920 entries, 0 to 4919
Columns: 134 entries, itching to Unnamed: 133
dtypes: float64(1), int64(132), object(1)
memory usage: 5.0+ MB


In [6]:
df.describe()

itching    skin_rash  nodal_skin_eruptions  continuous_sneezing  \
count  4920.000000  4920.000000           4920.000000          4920.000000   
mean      0.137805     0.159756              0.021951             0.045122   
std       0.344730     0.366417              0.146539             0.207593   
min       0.000000     0.000000              0.000000             0.000000   
25%       0.000000     0.000000              0.000000             0.000000   
50%       0.000000     0.000000              0.000000             0.000000   
75%       0.000000     0.000000              0.000000             0.000000   
max       1.000000     1.000000              1.000000             1.000000   

         shivering       chills   joint_pain  stomach_pain      acidity  \
count  4920.000000  4920.000000  4920.000000   4920.000000  4920.000000   
mean      0.021951     0.162195     0.139024      0.045122     0.045122   
std       0.146539     0.368667     0.346007      0.207593     0.207593   
min       0.000000     0.000000     0.000000      0.000000     0.000000   
25%       0.000000     0.000000     0.000000      0.000000     0.000000   
50%       0.000000     0.000000     0.000000      0.000000     0.000000   
75%       0.000000     0.000000     0.000000      0.000000     0.000000   
max       1.000000     1.000000     1.000000      1.000000     1.000000   

       ulcers_on_tongue  ...   blackheads     scurring  skin_peeling  \
count       4920.000000  ...  4920.000000  4920.000000   4920.000000   
mean           0.021951  ...     0.021951     0.021951      0.023171   
std            0.146539  ...     0.146539     0.146539      0.150461   
min            0.000000  ...     0.000000     0.000000      0.000000   
25%            0.000000  ...     0.000000     0.000000      0.000000   
50%            0.000000  ...     0.000000     0.000000      0.000000   
75%            0.000000  ...     0.000000     0.000000      0.000000   
max            1.000000  ...     1.000000     1.000000      1.000000   

       silver_like_dusting  small_dents_in_nails  inflammatory_nails  \
count          4920.000000           4920.000000         4920.000000   
mean              0.023171              0.023171            0.023171   
std               0.150461              0.150461            0.150461   
min               0.000000              0.000000            0.000000   
25%               0.000000              0.000000            0.000000   
50%               0.000000              0.000000            0.000000   
75%               0.000000              0.000000            0.000000   
max               1.000000              1.000000            1.000000   

           blister  red_sore_around_nose  yellow_crust_ooze  Unnamed: 133  
count  4920.000000           4920.000000        4920.000000           0.0  
mean      0.023171              0.023171           0.023171           NaN  
std       0.150461              0.150461           0.150461           NaN  
min       0.000000              0.000000           0.000000           NaN  
25%       0.000000              0.000000           0.000000           NaN  
50%       0.000000              0.000000           0.000000           NaN  
75%       0.000000              0.000000           0.000000           NaN  
max       1.000000              1.000000           1.000000           NaN  

[8 rows x 133 columns]

In [7]:
df.columns

Index(['itching', 'skin_rash', 'nodal_skin_eruptions', 'continuous_sneezing',
       'shivering', 'chills', 'joint_pain', 'stomach_pain', 'acidity',
       'ulcers_on_tongue',
       ...
       'scurring', 'skin_peeling', 'silver_like_dusting',
       'small_dents_in_nails', 'inflammatory_nails', 'blister',
       'red_sore_around_nose', 'yellow_crust_ooze', 'prognosis',
       'Unnamed: 133'],
      dtype='object', length=134)

In [10]:
df['prognosis'].unique()

array(['Fungal infection', 'Allergy', 'GERD', 'Chronic cholestasis',
       'Drug Reaction', 'Peptic ulcer diseae', 'AIDS', 'Diabetes ',
       'Gastroenteritis', 'Bronchial Asthma', 'Hypertension ', 'Migraine',
       'Cervical spondylosis', 'Paralysis (brain hemorrhage)', 'Jaundice',
       'Malaria', 'Chicken pox', 'Dengue', 'Typhoid', 'hepatitis A',
       'Hepatitis B', 'Hepatitis C', 'Hepatitis D', 'Hepatitis E',
       'Alcoholic hepatitis', 'Tuberculosis', 'Common Cold', 'Pneumonia',
       'Dimorphic hemmorhoids(piles)', 'Heart attack', 'Varicose veins',
       'Hypothyroidism', 'Hyperthyroidism', 'Hypoglycemia',
       'Osteoarthristis', 'Arthritis',
       '(vertigo) Paroymsal  Positional Vertigo', 'Acne',
       'Urinary tract infection', 'Psoriasis', 'Impetigo'], dtype=object)

In [147]:
# Checking for null
df.isnull().any() # Unname: 133 column has null values

itching                 False
skin_rash               False
nodal_skin_eruptions    False
continuous_sneezing     False
shivering               False
                        ...  
blister                 False
red_sore_around_nose    False
yellow_crust_ooze       False
prognosis               False
Unnamed: 133             True
Length: 134, dtype: bool

In [148]:
df['Unnamed: 133'].isna().sum() # 4920 null values in Unnamed: 133 column

4920

In [149]:
# dropping the column Unnamed: 133
df = df.drop('Unnamed: 133', axis=1)

In [150]:
df.isnull().any().sum()

0

In [151]:
# correlation matrix showing relation b/w each attribute 
corr_matrix = df.corr()
corr_matrix

itching  skin_rash  nodal_skin_eruptions  \
itching               1.000000   0.318158              0.326439   
skin_rash             0.318158   1.000000              0.298143   
nodal_skin_eruptions  0.326439   0.298143              1.000000   
continuous_sneezing  -0.086906  -0.094786             -0.032566   
shivering            -0.059893  -0.065324             -0.022444   
...                        ...        ...                   ...   
small_dents_in_nails -0.061573   0.331087             -0.023073   
inflammatory_nails   -0.061573   0.331087             -0.023073   
blister              -0.061573   0.331087             -0.023073   
red_sore_around_nose -0.061573   0.331087             -0.023073   
yellow_crust_ooze    -0.061573   0.331087             -0.023073   

                      continuous_sneezing  shivering    chills  joint_pain  \
itching                         -0.086906  -0.059893 -0.175905   -0.160650   
skin_rash                       -0.094786  -0.065324 -0.029324    0.171134   
nodal_skin_eruptions            -0.032566  -0.022444 -0.065917   -0.060200   
continuous_sneezing              1.000000   0.608981  0.446238   -0.087351   
shivering                        0.608981   1.000000  0.295332   -0.060200   
...                                   ...        ...       ...         ...   
small_dents_in_nails            -0.033480  -0.023073 -0.067765    0.359845   
inflammatory_nails              -0.033480  -0.023073 -0.067765    0.359845   
blister                         -0.033480  -0.023073 -0.067765   -0.061889   
red_sore_around_nose            -0.033480  -0.023073 -0.067765   -0.061889   
yellow_crust_ooze               -0.033480  -0.023073 -0.067765   -0.061889   

                      stomach_pain   acidity  ulcers_on_tongue  ...  \
itching                   0.202850 -0.086906         -0.059893  ...   
skin_rash                 0.161784 -0.094786         -0.065324  ...   
nodal_skin_eruptions     -0.032566 -0.032566         -0.022444  ...   
continuous_sneezing      -0.047254 -0.047254         -0.032566  ...   
shivering                -0.032566 -0.032566         -0.022444  ...   
...                            ...       ...               ...  ...   
small_dents_in_nails     -0.033480 -0.033480         -0.023073  ...   
inflammatory_nails       -0.033480 -0.033480         -0.023073  ...   
blister                  -0.033480 -0.033480         -0.023073  ...   
red_sore_around_nose     -0.033480 -0.033480         -0.023073  ...   
yellow_crust_ooze        -0.033480 -0.033480         -0.023073  ...   

                      pus_filled_pimples  blackheads  scurring  skin_peeling  \
itching                        -0.059893   -0.059893 -0.059893     -0.061573   
skin_rash                       0.320859    0.320859  0.320859      0.331087   
nodal_skin_eruptions           -0.022444   -0.022444 -0.022444     -0.023073   
continuous_sneezing            -0.032566   -0.032566 -0.032566     -0.033480   
shivering                      -0.022444   -0.022444 -0.022444     -0.023073   
...                                  ...         ...       ...           ...   
small_dents_in_nails           -0.023073   -0.023073 -0.023073      0.946120   
inflammatory_nails             -0.023073   -0.023073 -0.023073      0.946120   
blister                        -0.023073   -0.023073 -0.023073     -0.023720   
red_sore_around_nose           -0.023073   -0.023073 -0.023073     -0.023720   
yellow_crust_ooze              -0.023073   -0.023073 -0.023073     -0.023720   

                      silver_like_dusting  small_dents_in_nails  \
itching                         -0.061573             -0.061573   
skin_rash                        0.331087              0.331087   
nodal_skin_eruptions            -0.023073             -0.023073   
continuous_sneezing             -0.033480             -0.033480   
shivering                       -0.023073             -0.023073   
...                                   ...                   ...  

In [152]:
# Separating the label from the data
label = df[['prognosis']]
label

prognosis
0                            Fungal infection
1                            Fungal infection
2                            Fungal infection
3                            Fungal infection
4                            Fungal infection
...                                       ...
4915  (vertigo) Paroymsal  Positional Vertigo
4916                                     Acne
4917                  Urinary tract infection
4918                                Psoriasis
4919                                 Impetigo

[4920 rows x 1 columns]

In [153]:
# Converting label category to numerical
from sklearn.preprocessing import OrdinalEncoder
ord_encod = OrdinalEncoder()
prognosis_encoded = ord_encod.fit_transform(label)
prognosis_encoded

array([[15.],
       [15.],
       [15.],
       ...,
       [38.],
       [35.],
       [27.]])

In [158]:
# Checking unique values after encoding
np.unique(prognosis_encoded, return_index=False)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40.])

In [159]:
# Adding encoded value back to dataframe
df['prognosis'] = prognosis_encoded
df


itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
0           1          1                     1                    0   
1           0          1                     1                    0   
2           1          0                     1                    0   
3           1          1                     0                    0   
4           1          1                     1                    0   
...       ...        ...                   ...                  ...   
4915        0          0                     0                    0   
4916        0          1                     0                    0   
4917        0          0                     0                    0   
4918        0          1                     0                    0   
4919        0          1                     0                    0   

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
0             0       0           0             0        0                 0   
1             0       0           0             0        0                 0   
2             0       0           0             0        0                 0   
3             0       0           0             0        0                 0   
4             0       0           0             0        0                 0   
...         ...     ...         ...           ...      ...               ...   
4915          0       0           0             0        0                 0   
4916          0       0           0             0        0                 0   
4917          0       0           0             0        0                 0   
4918          0       0           1             0        0                 0   
4919          0       0           0             0        0                 0   

      ...  blackheads  scurring  skin_peeling  silver_like_dusting  \
0     ...           0         0             0                    0   
1     ...           0         0             0                    0   
2     ...           0         0             0                    0   
3     ...           0         0             0                    0   
4     ...           0         0             0                    0   
...   ...         ...       ...           ...                  ...   
4915  ...           0         0             0                    0   
4916  ...           1         1             0                    0   
4917  ...           0         0             0                    0   
4918  ...           0         0             1                    1   
4919  ...           0         0             0                    0   

      small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                        0                   0        0                     0   
1                        0                   0        0                     0   
2                        0                   0        0                     0   
3                        0                   0        0                     0   
4                        0                   0        0                     0   
...                    ...                 ...      ...                   ...   
4915                     0                   0        0                     0   
4916                     0                   0        0                     0   
4917                     0                   0        0                     0   
4918                     1                   1        0                     0   
4919                     0                   0        1                     1   

      yellow_crust_ooze  prognosis  
0                     0       15.0  
1                     0       15.0  
2                     0       15.0  
3                     0       15.0  
4                     0       15.0  
...                 ...        ...  
4915                  0        0.0  
4916                  0        2.0  
4917                  0       38.0  
4918    

In [160]:
# Separating input and label for training the model
input_data = df.drop('prognosis', axis=1)
label = df['prognosis'].copy()
label

0       15.0
1       15.0
2       15.0
3       15.0
4       15.0
        ... 
4915     0.0
4916     2.0
4917    38.0
4918    35.0
4919    27.0
Name: prognosis, Length: 4920, dtype: float64

In [101]:
# Separating the data in training and testing
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(input_data, label, test_size=0.3,  random_state=42)

# Using logistic regression 

In [161]:
# Using logistic regression model 
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(random_state=42).fit(X_train, Y_train)

In [162]:
prediction_X = clf.predict(X_train)

In [163]:
# checking score of prediction
clf.score(X_train, Y_train)

1.0

In [164]:
prediction_test = clf.predict(X_test)

In [165]:
# score for test data prediction
clf.score(X_test, Y_test)

1.0

In [107]:
# Using cross validation score
from sklearn.model_selection import cross_val_score
cross_val_score(clf, X_test, Y_test, cv=3)

array([1., 1., 1.])

In [108]:
from sklearn.metrics import accuracy_score, confusion_matrix
accuracy_score(prediction_test, Y_test)

1.0

# Using Decision Tree Classifier model

In [172]:
from sklearn.tree import DecisionTreeClassifier
tree_clf = DecisionTreeClassifier(random_state=42)
tree_clf.fit(X_train, Y_train)

DecisionTreeClassifier(random_state=42)

In [173]:
tree_clf.score(X_train, Y_train)

1.0

In [174]:
test_pred = tree_clf.predict(X_test)

In [175]:
accuracy_score(test_pred, Y_test)

1.0

In [113]:
tree_clf.score(X_test, Y_test)

1.0

In [177]:
# with cv = 3 
cross_val_score(tree_clf, X_test, Y_test, cv=3)

array([0.96138211, 0.98577236, 0.96544715])

# Using random forest classifier

In [178]:
3# By increaing max_depth in random forest, we can increase accuracy
from sklearn.ensemble import RandomForestClassifier
r_clf = RandomForestClassifier(max_depth=10, random_state=42)
r_clf.fit(X_train, Y_train)

RandomForestClassifier(max_depth=10, random_state=42)

In [179]:
r_test_set = r_clf.predict(X_test)

In [180]:
accuracy_score(r_test_set, Y_test)

1.0

In [181]:
cross_val_score(r_clf, X_test, Y_test, cv=5)

array([0.99662162, 0.99661017, 1.        , 1.        , 1.        ])

# Using stratifiedkfold method and cloning logistic regression clf

In [119]:

from sklearn.model_selection import StratifiedKFold
from sklearn.base import clone
skfolds = StratifiedKFold(n_splits=3, random_state=42, shuffle=True)
for train_index, test_index in skfolds.split(X_train, Y_train):
    clone_clf = clone(clf)
    X_train_folds = X_train.iloc[train_index]
    y_train_folds = Y_train.iloc[train_index]
    X_test_fold = X_train.iloc[test_index]
    y_test_fold = Y_train.iloc[test_index]
    clone_clf.fit(X_train_folds, y_train_folds)
    y_pred = clone_clf.predict(X_test_fold)
    n_correct = sum(y_pred == y_test_fold)
    print(n_correct / len(y_pred))

1.0
1.0
1.0


# Using SVC classifier

In [120]:
# Using gridsearchcv for best parameters
from sklearn.model_selection import GridSearchCV
from sklearn import svm
param = [
    {'C': [1, 20, 50, 100], 'kernel': ['linear']},
    {'C': [1, 50, 100, 150], 'kernel': ['sigmoid'], 'gamma': [0.1, 0.01, 0.001]}, 
    {'C': [10, 50, 80, 120], 'kernel': ['rbf'], 'gamma': [0.1, 0.01, 0.001]}
]
svc = svm.SVC(probability=True)
svc_clf = GridSearchCV(svc, param)
svc_clf.fit(X_train, Y_train)

GridSearchCV(estimator=SVC(probability=True),
             param_grid=[{'C': [1, 20, 50, 100], 'kernel': ['linear']},
                         {'C': [1, 50, 100, 150], 'gamma': [0.1, 0.01, 0.001],
                          'kernel': ['sigmoid']},
                         {'C': [10, 50, 80, 120], 'gamma': [0.1, 0.01, 0.001],
                          'kernel': ['rbf']}])

In [121]:
# Checking for best estimators from param
svc_clf.best_estimator_

SVC(C=1, kernel='linear', probability=True)

In [122]:
svc_clf.best_score_

1.0

In [123]:
svc_clf.best_params_

{'C': 1, 'kernel': 'linear'}

In [124]:
grid_test_pred = svc_clf.predict(X_test)

In [125]:
accuracy_score(grid_test_pred, Y_test)

1.0

In [126]:
confusion_matrix(grid_test_pred, Y_test)

array([[32,  0,  0, ...,  0,  0,  0],
       [ 0, 39,  0, ...,  0,  0,  0],
       [ 0,  0, 41, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ..., 36,  0,  0],
       [ 0,  0,  0, ...,  0, 37,  0],
       [ 0,  0,  0, ...,  0,  0, 39]], dtype=int64)

In [182]:
df_test = pd.read_csv('Testing.csv')
df_test.head()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          0                     0                    1          1   
2        0          0                     0                    0          0   
3        1          0                     0                    0          0   
4        1          1                     0                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       1           0             0        0                 0  ...   
2       0           0             1        1                 1  ...   
3       0           0             0        0                 0  ...   
4       0           0             1        0                 0  ...   

   blackheads  scurring  skin_peeling  silver_like_dusting  \
0           0         0             0                    0   
1           0         0             0                    0   
2           0         0             0                    0   
3           0         0             0                    0   
4           0         0             0                    0   

   small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                     0                   0        0                     0   
1                     0                   0        0                     0   
2                     0                   0        0                     0   
3                     0                   0        0                     0   
4                     0                   0        0                     0   

   yellow_crust_ooze            prognosis  
0                  0     Fungal infection  
1                  0              Allergy  
2                  0                 GERD  
3                  0  Chronic cholestasis  
4                  0        Drug Reaction  

[5 rows x 133 columns]

In [183]:
df_test_label = df_test[['prognosis']]
df_test_label

prognosis
0                          Fungal infection
1                                   Allergy
2                                      GERD
3                       Chronic cholestasis
4                             Drug Reaction
5                       Peptic ulcer diseae
6                                      AIDS
7                                 Diabetes 
8                           Gastroenteritis
9                          Bronchial Asthma
10                            Hypertension 
11                                 Migraine
12                     Cervical spondylosis
13             Paralysis (brain hemorrhage)
14                                 Jaundice
15                                  Malaria
16                              Chicken pox
17                                   Dengue
18                                  Typhoid
19                              hepatitis A
20                              Hepatitis B
21                              Hepatitis C
22                              Hepatitis D
23                              Hepatitis E
24                      Alcoholic hepatitis
25                             Tuberculosis
26                              Common Cold
27                                Pneumonia
28             Dimorphic hemmorhoids(piles)
29                             Heart attack
30                           Varicose veins
31                           Hypothyroidism
32                          Hyperthyroidism
33                             Hypoglycemia
34                          Osteoarthristis
35                                Arthritis
36  (vertigo) Paroymsal  Positional Vertigo
37                                     Acne
38                  Urinary tract infection
39                                Psoriasis
40                                 Impetigo
41                         Fungal infection

In [184]:
df_test_label = ord_encod.fit_transform(df_test_label)

In [187]:
df_test = df_test.drop('prognosis', axis=1)

In [188]:
df_test['prognosis'] = df_test_label

In [189]:
df_test.head()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          0                     0                    1          1   
2        0          0                     0                    0          0   
3        1          0                     0                    0          0   
4        1          1                     0                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       1           0             0        0                 0  ...   
2       0           0             1        1                 1  ...   
3       0           0             0        0                 0  ...   
4       0           0             1        0                 0  ...   

   blackheads  scurring  skin_peeling  silver_like_dusting  \
0           0         0             0                    0   
1           0         0             0                    0   
2           0         0             0                    0   
3           0         0             0                    0   
4           0         0             0                    0   

   small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                     0                   0        0                     0   
1                     0                   0        0                     0   
2                     0                   0        0                     0   
3                     0                   0        0                     0   
4                     0                   0        0                     0   

   yellow_crust_ooze  prognosis  
0                  0       15.0  
1                  0        4.0  
2                  0       16.0  
3                  0        9.0  
4                  0       14.0  

[5 rows x 133 columns]

In [190]:
df_test_data = df_test.drop('prognosis', axis=1)

In [191]:
df_test_label = df_test['prognosis'].copy()

In [192]:
# using svc classifier
df_test_pred = svc_clf.predict(df_test_data)

In [193]:
accuracy_score(df_test_pred, df_test_label)

1.0

In [194]:
# using logistic regression
df_test_pred = clf.predict(df_test_data)
accuracy_score(df_test_pred, df_test_label)

1.0